package httpheaders

const (
	ApplicationFormURLEncoded = "application/x-www-form-urlencoded"
	ApplicationJSON           = "application/json"
	ApplicationJavascript     = "application/javascript"
	ApplicationLDPJSON        = "application/ld+json"
	ApplicationOctetStream    = "application/octet-stream"
	ApplicationPDF            = "application/pdf"
	ApplicationXML            = "application/xml"
	AudioMPEG                 = "audio/mpeg"
	AudioOGG                  = "audio/ogg"
	AudioWAV                  = "audio/wav"
	FontWOFF                  = "font/woff"
	FontWOFF2                 = "font/woff2"
	ImageBMP                  = "image/bmp"
	ImageGIF                  = "image/gif"
	ImageJPEG                 = "image/jpeg"
	ImagePNG                  = "image/png"
	ImageSVG                  = "image/svg+xml"
	ImageWEBP                 = "image/webp"
	MultipartForm             = "multipart/form-data"
	TextCSV                   = "text/csv"
	TextCSS                   = "text/css"
	TextHTML                  = "text/html"
	TextPlain                 = "text/plain"
	TextXML                   = "text/xml"
	VideoMP4                  = "video/mp4"
	VideoOGG                  = "video/ogg"
	VideoWebM                 = "video/webm"
)
